"""
How you get a species that nothing spawns in the wild.

The spawner tables (data/json/spawns.json) answer "where does it roam" for most
of the Paldeck. The rest come from somewhere else, and the pak says where for
all but a handful:

  raid        summoned at an altar from a slab; the kill drops an egg that hatches
              into the species (RAID_<species> rows flagged IsRaidBoss in
              DT_PalMonsterParameter)
  meteor      lands with a meteor event, level by region
              (DT_SupplyIncident_Pal_<Region><n> tables)
  world_tree  a placed boss inside the World Tree, catchable (hand-kept: the
              only copy is in the level cells, which no table reflects)
  story       caught during the main quest (hand-kept)
  none        not obtainable at all (the pak flags the base form uncapturable)

data/json/obtain.json is generated by scripts/datagen/generate_obtain.py from
build_obtain(); the deck and the Best workers tool read it through obtain_spawn()
and obtain_levels().
"""
from collections import defaultdict
from typing import Dict, Iterable, List, Optional

# Species save-pal's pals.json gets wrong for the deck. Panthalus (KingWhale) is
# marked disabled upstream; the pak gives it deck number 203, no uncapturable
# flag, and the story catch. The loader applies these onto the species row.
SPECIES_OVERRIDES: Dict[str, Dict] = {
    'KingWhale': {'disabled': False},
}

# The rows no pak table carries (see the module docstring). Levels: the World
# Tree bosses are level 78 encounters (Shinespore Root, Rotmist Root); Panthalus
# is the level 70 story fight before the World Tree.
HAND_ROWS: Dict[str, Dict] = {
    'Mothman': {'how': 'world_tree', 'min_level': 78, 'max_level': 78, 'alpha': True, 'place': 'Shinespore Root'},
    'FlowerPrince': {'how': 'world_tree', 'min_level': 78, 'max_level': 78, 'alpha': True, 'place': 'Rotmist Root'},
    'KingWhale': {'how': 'story', 'min_level': 70, 'max_level': 70, 'alpha': True, 'place': 'Panthalus quest, before the World Tree'},
    'WorldTreeDragon': {'how': 'none'},
}

RAID_PREFIX = 'RAID_'
BOSS_PREFIX = 'BOSS_'
SUPPLY_PREFIX = 'DT_SupplyIncident_Pal'
LEVEL_KINDS = ('meteor', 'world_tree', 'story')   # the kinds with a level you can plan around
MIN_RAID_SPECIES = 4
MIN_METEOR_SPECIES = 2


def _raid_species(row_id: str) -> str:
    """RAID_NightLady_Dark_2 -> NightLady_Dark; RAID_YakushimaBoss002_Hand_Left -> YakushimaBoss002."""
    sid = row_id[len(RAID_PREFIX):]
    if sid.endswith('_2'):                      # the harder second-tier row
        sid = sid[:-2]
    for suffix in ('_Hand_Left', '_Hand_Right', '_Head'):
        if sid.endswith(suffix):                # multi-part bosses: one species
            sid = sid[:-len(suffix)]
    return sid


def _region(table_name: str) -> str:
    """DT_SupplyIncident_Pal_DarkIsland_03 -> DarkIsland; DT_SupplyIncident_Pal_Grass02 -> Grass."""
    rest = table_name[len(SUPPLY_PREFIX):].strip('_')
    return rest.rstrip('0123456789').rstrip('_') or 'Any'


def build_obtain(monster_rows: Dict[str, Dict], supply_tables: Dict[str, Dict[str, Dict]],
                 hand: Optional[Dict[str, Dict]] = None, known: Optional[Iterable[str]] = None) -> Dict:
    """{species: {how, ...}} from the pak tables plus the hand-kept rows.

    `monster_rows` is DT_PalMonsterParameter; `supply_tables` maps each
    DT_SupplyIncident_Pal_* table name to its rows. Hand rows win over derived
    ones, so a species can be re-classified without touching the pak logic.
    `known` (pals.json ids) drops rows for characters the app has no species
    for -- the collab raid bosses.
    """
    out: Dict[str, Dict] = {}
    known_ids = set(known) if known is not None else None

    for row_id, r in monster_rows.items():
        if row_id.startswith(RAID_PREFIX) and r.get('IsRaidBoss'):
            sid = _raid_species(row_id)
            out.setdefault(sid, {'how': 'raid', 'alpha': False})

    meteor: Dict[str, Dict] = {}
    for table, rows in supply_tables.items():
        region = _region(table)
        for r in rows.values():
            cid = r.get('CharacterID')
            cid = cid.get('Key') if isinstance(cid, dict) else cid
            if not cid or cid == 'None':
                continue
            alpha = cid.startswith(BOSS_PREFIX)
            sid = cid[len(BOSS_PREFIX):] if alpha else cid
            lv = int(r.get('Level') or 0)
            m = meteor.setdefault(sid, {'how': 'meteor', 'alpha': False, 'min_level': lv, 'max_level': lv, 'regions': {}})
            m['alpha'] = m['alpha'] or alpha
            m['min_level'] = min(m['min_level'], lv)
            m['max_level'] = max(m['max_level'], lv)
            reg = m['regions'].setdefault(region, [lv, lv])
            reg[0], reg[1] = min(reg[0], lv), max(reg[1], lv)
    for sid, m in meteor.items():
        m['regions'] = {k: v for k, v in sorted(m['regions'].items(), key=lambda kv: kv[1][0])}
        if out.get(sid, {}).get('how') != 'raid':      # a raid egg outranks a meteor sighting
            out[sid] = m

    for sid, row in (HAND_ROWS if hand is None else hand).items():
        out[sid] = dict(row)
    if known_ids is not None:
        out = {sid: row for sid, row in out.items() if sid in known_ids}
    return {'species': out}


def obtain_spawn(obtain: Dict, sid: str) -> Optional[Dict]:
    """A spawn-shaped summary ({how, min_level, max_level, night, alpha, groups}) for a species
    with no wild spawner, or None when the table has nothing on it either."""
    row = ((obtain or {}).get('species') or {}).get(sid)
    if not row:
        return None
    return {
        'how': row['how'],
        'min_level': row.get('min_level'),
        'max_level': row.get('max_level'),
        'night': False,
        'alpha': bool(row.get('alpha')),
        'groups': 0,
        'regions': row.get('regions'),
        'place': row.get('place'),
    }


def obtain_levels(obtain: Dict) -> Dict[str, int]:
    """{species: lowest level} for every obtainable kind that has a level -- what the Best workers
    catch list merges under its wild levels (wild wins when a species has both)."""
    out: Dict[str, int] = {}
    for sid, row in ((obtain or {}).get('species') or {}).items():
        if row.get('how') in LEVEL_KINDS and row.get('min_level') is not None:
            out[sid] = int(row['min_level'])
    return out


def obtain_hows(obtain: Dict) -> Dict[str, str]:
    """{species: how} for the same set as obtain_levels()."""
    return {sid: row['how'] for sid, row in ((obtain or {}).get('species') or {}).items()
            if row.get('how') in LEVEL_KINDS and row.get('min_level') is not None}
