#!/usr/bin/env python3
"""
Generate data/json/schematics.json -- what each schematic (blueprint item) unlocks.

Every schematic in items.json carries the same generic blueprint icon; the game
keeps the link to the product in its recipe tables, read from the client pak
with the CUE4Parse extractor (scripts/datagen/extractor):

  DT_ItemRecipeDataTable    Product_Id + UnlockItemID  (item recipes a schematic unlocks)
  DT_BuildObjectDataTable   MapObjectId + BlueprintItemID  (buildings a schematic unlocks)

The output maps blueprint id -> {product, kind}. Icons, names and rarity are
resolved at runtime from items.json / buildings.json (backend/common/schematics.py),
so the file stays small and survives a save-pal resync untouched.

Usage:
  python3 scripts/datagen/generate_schematics.py            # extract from the pak
  python3 scripts/datagen/generate_schematics.py --src DIR  # DIR has recipes.json + buildobjects.json
  python3 scripts/datagen/generate_schematics.py --dry-run
"""

import argparse
import collections
import json
import os
import subprocess
import sys
from pathlib import Path

from savepal import ROOT as REPO, DATA_JSON
from backend.common.schematics import MIN_SCHEMATICS, blueprint_ids, build_schematics

OUT_PATH = DATA_JSON / 'schematics.json'
EXTRACTOR = REPO / 'scripts' / 'datagen' / 'extractor' / 'bin' / 'Release' / 'net8.0' / 'pal-extract'
CACHE = REPO / 'scripts' / 'datagen' / '.cache' / 'schematics'
PAK_DIR = Path(os.environ.get('PALWORLD_PAK_DIR', str(Path.home() / '.gamedata' / 'palworld-pak-data')))
USMAP = os.environ.get('PALWORLD_USMAP', '')

TABLES = {'recipes.json': 'DT_ItemRecipeDataTable', 'buildobjects.json': 'DT_BuildObjectDataTable'}


def extract(src: Path) -> None:
    if not EXTRACTOR.exists():
        raise SystemExit(f'error: extractor not built: {EXTRACTOR} (see scripts/datagen/README.md)')
    if not PAK_DIR.is_dir() or not USMAP or not Path(USMAP).exists():
        raise SystemExit('error: PALWORLD_PAK_DIR / PALWORLD_USMAP missing -- required to read the recipe tables')
    src.mkdir(parents=True, exist_ok=True)
    env = {**os.environ, 'PALWORLD_PAK_DIR': str(PAK_DIR), 'PALWORLD_USMAP': USMAP}
    for fname, table in TABLES.items():
        print(f'extracting {table} ...')
        r = subprocess.run([str(EXTRACTOR), 'dt', table, str(src / fname)], env=env, stdout=subprocess.DEVNULL)
        if r.returncode != 0:
            raise SystemExit(f'error: extractor failed on {table}')


def load_rows(src: Path, fname: str) -> dict:
    with open(src / fname, encoding='utf-8') as f:
        data = json.load(f)
    rows = data.get('Rows') if isinstance(data, dict) else None
    if not rows:
        raise SystemExit(f'error: {src / fname} has no Rows')
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', type=Path, help='dir with recipes.json + buildobjects.json (skips the extractor)')
    ap.add_argument('--dry-run', action='store_true', help='report only, do not write')
    args = ap.parse_args()

    src = args.src or CACHE
    if not args.src:
        extract(src)

    with open(DATA_JSON / 'items.json', encoding='utf-8') as f:
        items = json.load(f)
    with open(DATA_JSON / 'buildings.json', encoding='utf-8') as f:
        buildings = json.load(f)

    table, unmatched = build_schematics(load_rows(src, 'recipes.json').values(),
                                        load_rows(src, 'buildobjects.json').values(), items, buildings)
    kinds = collections.Counter(e['kind'] for e in table.values())
    print(f'\n{len(table)} of {len(blueprint_ids(items))} schematics resolved '
          f'({kinds["item"]} items, {kinds["building"]} buildings)')
    if unmatched:
        print(f'{len(unmatched)} schematic(s) nothing unlocks (retired ids expected): ' + ', '.join(unmatched))
    if len(table) < MIN_SCHEMATICS:
        print(f'\nWARNING: only {len(table)} resolved (expected >= {MIN_SCHEMATICS}) -- stale usmap? partial extraction?')

    if OUT_PATH.exists():
        with open(OUT_PATH, encoding='utf-8') as f:
            old = json.load(f).get('schematics') or {}
        gained, lost = sorted(set(table) - set(old)), sorted(set(old) - set(table))
        changed = sorted(k for k in table if k in old and old[k] != table[k])
        print(f'vs committed: {len(old)} -> {len(table)}; +{len(gained)} / -{len(lost)} / {len(changed)} retargeted')
        for label, ids in (('gained', gained), ('LOST', lost), ('retargeted', changed)):
            if ids:
                print(f'  {label}: ' + ', '.join(ids[:12]) + (' ...' if len(ids) > 12 else ''))

    if args.dry_run:
        print('\n--dry-run: not written')
        return 0
    doc = {
        '_comment': 'Generated by scripts/datagen/generate_schematics.py from the game\'s DT_ItemRecipeDataTable '
                    '(UnlockItemID) and DT_BuildObjectDataTable (BlueprintItemID). schematics[blueprint_id] = '
                    'the item or building it unlocks; icon, name and rarity are resolved at runtime from '
                    'items.json / buildings.json. Do not edit by hand.',
        'schematics': table,
    }
    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        json.dump(doc, f, ensure_ascii=False, indent=1)
        f.write('\n')
    print(f'\nwrote {OUT_PATH.relative_to(REPO)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
